### ISSUE TITLE
Coin multiplier permission doesnt work unless plugin is reloaded.

### ISSUE THREAD

**Issue by Kitkatwithmilk** [JustEli/Coins#23]
Coin multiplier permission doesnt work unless plugin is reloaded.

**Comment by JustEli** [comment]
yeah i think that is fine for how it is.
in fact: when a permission for someone changes, it doesn't work until the plugin is reloaded, but it will work fine if they have the permission when they join the server after reboot
it's a little inefficient to update the multiplier of a player every time they kill a mob, that's why it works like this
