### ISSUE TITLE
Strange lag

### ISSUE THREAD

**Issue by Kapitowa** [JustEli/Coins#27]
Strange lag, can it be fixable?
![image](https://user-images.githubusercontent.com/62211966/98989228-4031b200-2542-11eb-91f5-d73641edbc7b.png)

**Comment by JustEli** [comment]
this doesn't say much to me, this function is ran every time coins are dropped

i haven't come across this before, and i was wondering if you could give a bunch of more details, maybe even the entire timings report (can do it through discord if you want at Eli#1561) but at least:
- what version number and Minecraft version of Paper or Spigot are you using
- what version of Coins
- how often does this occur
- when does this occur, at specific times?
- how much memory does the server run on
- is it even a premium host? because i know that very cheap hosts will make any plugin lag
- maybe it's useful for me to also see the config.yml you have, if you modified it
